ifdef::env-github[]
:supported: :white_check_mark:
:unsupported: :x:
endif::[]

ifndef::env-github[]
:supported: icon:check-square[2x,role=green]
:unsupported: icon:times[2x,role=red]
endif::[]

= Do you have a question?

TIP: Search Stack Overflow first; discuss if necessary

If you're unsure why something isn't working or wondering if there is a better
way of doing it please check on **Stack Overflow** first and if necessary start
a discussion. Use relevant tags among the ones we monitor for that purpose:

 - https://stackoverflow.com/questions/tagged/reactor-netty[`reactor-netty`] for specific reactor-netty questions
 - https://stackoverflow.com/questions/tagged/project-reactor[`project-reactor`] for generic reactor questions

If you prefer real-time discussion, we also have a few **Gitter channels**:

 - https://gitter.im/reactor/reactor[`reactor`] is the historic most active one, where most of the community can help
 - https://gitter.im/reactor/reactor-core[`reactor-core`] is intended for more advanced pinpointed discussions around the inner workings of the library
 - https://gitter.im/reactor/reactor-netty[`reactor-netty`] is intended for netty-specific questions

Refer to each project's README for potential other sources of information.
	
We generally discourage opening GitHub issues for questions, in favor of the two channels above.

= Our policy on **deprecations**

When dealing with deprecations, given a version `A.B.C`, we'll ensure that:

* deprecations introduced in version `A`.`B`.`x` will be removed **no sooner than** in
version released near or after the end of commercial support for `A`.`B`.`x` line or
any prior lines supported longer than `A`.`B.`x` line
* we'll strive to mention the following in the deprecation javadoc:
** target minimum version for removal
** pointers to replacements for the deprecated method
** version in which method was deprecated

TIP: If deprecation was introduced in 2022.0.12 release BOM, it could be removed not
earlier than 2026-12-31 since that is the end of commercial support for the 2020.0.x
line which has longer support than 2022.0.x line.
That means that only the iteration released in 2026 or later could safely remove given
deprecations.

TIP: This policy is officially in effect as of January 2024, for all modules in `2020.0` BOMs and newer release trains.

NOTE: Deprecation removal targets are not a hard commitment, and the deprecated methods **could live on further than these minimum target GA versions** (ie. only the most problematic deprecated methods will be removed aggressively).

WARNING: That said, deprecated code that has outlived its minimum removal target version may be removed in any subsequent release (including patch releases, aka service releases) without further notice. So users should still strive to update their code as early as possible.

= Active Development

The following table summarises the development status of the various Reactor release trains:

|=======
| Version                                                | Initial Release | End of Support            | End of Commercial Support*

| 2023.0.x (core 3.6.x, netty 1.1.x)                     | 2023.11.14      | 2025-08-31 {supported}    | 2026-12-31 {supported}
| 2022.0.x (core 3.5.x, netty 1.1.x)                     | 2022.11.08      | 2024-08-31 {supported}    | 2025-12-31 {supported}
| 2020.0.x (codename Europium) (core 3.4.x, netty 1.0.x) | 2020.10.26      | 2024-12-31 {supported}    | 2026-12-31 {supported}
|=======

NOTE:  *About commercial support* *(***)*:
       This page shows the current state of project releases and does not define the
commercial support policy. Please refer to the https://tanzu.vmware.com/spring-runtime[official support policy] for more information.
