ifdef::env-github[]
:supported: :white_check_mark:
:unsupported: :x:
endif::[]

ifndef::env-github[]
:supported: icon:check-square[2x,role=green]
:unsupported: icon:times[2x,role=red]
endif::[]

= Do you have a question?

TIP: Search Stack Overflow first; discuss if necessary

If you're unsure why something isn't working or wondering if there is a better
way of doing it please check on **Stack Overflow** first and if necessary start
a discussion. Use relevant tags among the ones we monitor for that purpose:

 - https://stackoverflow.com/questions/tagged/reactor-netty[`reactor-netty`] for specific reactor-netty questions
 - https://stackoverflow.com/questions/tagged/project-reactor[`project-reactor`] for generic reactor questions

If you prefer real-time discussion, we also have a few **Gitter channels**:

 - https://gitter.im/reactor/reactor[`reactor`] is the historic most active one, where most of the community can help
 - https://gitter.im/reactor/reactor-core[`reactor-core`] is intended for more advanced pinpointed discussions around the inner workings of the library
 - https://gitter.im/reactor/reactor-netty[`reactor-netty`] is intended for netty-specific questions

Refer to each project's README for potential other sources of information.
	
We generally discourage opening GitHub issues for questions, in favor of the two channels above.

= Our policy on **deprecations**

When dealing with deprecations, given a version `A.B.C`, we'll ensure that:

 * deprecations introduced in version `A`.`B`.`0` will be removed **no sooner than** version `A`.**`B+1`**.`0`
 * deprecations introduced in version `A`.`B`.`1+` will be removed **no sooner than** version `A`.**`B+2`**.`0`
 * we'll strive to mention the following in the deprecation javadoc:
  ** target minimum version for removal
  ** pointers to replacements for the deprecated method
  ** version in which method was deprecated

TIP: This policy is officially in effect as of January 2021, for all modules in `2020.0` BOMs and newer release trains, as well as `Dysprosium` releases after `Dysprosium-SR15`.

NOTE: Deprecation removal targets are not a hard commitment, and the deprecated methods **could live on further than these minimum target GA versions** (ie. only the most problematic deprecated methods will be removed aggressively).

WARNING: That said, deprecated code that has outlived its minimum removal target version may be removed in any subsequent release (including patch releases, aka service releases) without further notice. So users should still strive to update their code as early as possible.

= Support Timeline

The following table summarises the support dates for each individual project followed by the BOM support.

|===
|Version |Initial OSS Release |OSS Support End |Commercial Support (+*+) End |Published in BOM

|*reactor-core*
|
|
|
|

|3.6
|2023-11-14
|2025-08-31
|2026-12-31
|2023

|3.6
|2022-11-08
|2024-08-31
|2025-12-31
|2022

|3.6
|2020-10-26
|2024-08-31
|2025-12-31
|2020

|*reactor-netty*
|
|
|
|

|1.1
|2023-11-14
|2025-08-31
|2026-12-31
|2022, 2023

|1.0
|2020-10-26
|2024-08-31
|2025-12-31
|2020

|*reactor-kafka*
|
|
|
|

|1.3
|2023-11-14
|2025-08-31
|2026-12-31
|2020, 2022, 2023

|*reactor-pool*
|
|
|
|

|1.0
|2023-11-14
|2025-08-31
|2026-12-31
|2022, 2023

|0.2
|2020-10-26
|2024-08-31
|2025-12-31
|2020

|*reactor-addons*
|
|
|
|

|3.5
|2023-11-14
|2025-08-31
|2026-12-31
|2022, 2023

|3.4
|2020-10-26
|2024-08-31
|2025-12-31
|2020

|*reactor-kotlin-extensions*
|
|
|
|

|1.2
|2023-11-14
|2025-08-31
|2026-12-31
|2022, 2023

|1.1
|2020-10-26
|2024-08-31
|2025-12-31
|2020

|*reactor-rabbitmq*
|
|
|
|

|1.5
|2020-10-26
|2024-08-31
|2025-12-31
|2020

|*reactor-bom*
|
|
|
|

|2023
|2023-11-14
|2025-08-31
|2026-12-31
|-

|2022
|2022-11-08
|2024-08-31
|2025-12-31
|-

|2020
|2020-10-26
|2024-08-31
|2025-12-31
|-

|===

NOTE: *(+*+) Commercial Support*
    For more information visit https://spring.io/support[Spring Support page].
